<?php

declare(strict_types=1);

namespace Automapper\Bench;

use Automapper\Bench\Doctrine\DoctrineFixture;
use Doctrine\ORM\EntityManagerInterface;
use PhpBench\Attributes\BeforeMethods;
use PhpBench\Attributes\Groups;
use PhpBench\Attributes\Iterations;
use PhpBench\Attributes\ParamProviders;
use PhpBench\Attributes\Revs;

/**
 * Doctrine ObjectHydrator against the hydrators generated by AutoMapper, on the same SQL.
 *
 * `AutoMapper` subjects use AutoMapperEntityManager, which leaves the entity persisters (find(), lazy collections)
 * to Doctrine: with lazy collections, only the query loading the authors uses a generated hydrator.
 *
 * `benchDbalFetch` is the cost of fetching the rows without any hydration, and `benchHandwrittenDto` a hand
 * written hydration into detached DTOs: the floor without unit of work. Every other subject returns managed
 * entities. The equivalence of the results is checked by `php bin/verify.php`.
 *
 * Each iteration starts with an empty unit of work, so revolutions are kept to 1: a second revolution would
 * find the entities already managed and measure a different path.
 *
 * Run with:
 *   php vendor/bin/phpbench run src/DoctrineHydrationBench.php --report=aggregate
 */
#[Revs(1)]
#[Iterations(15)]
#[BeforeMethods('setUp')]
#[Groups(['doctrine'])]
class DoctrineHydrationBench
{
    private EntityManagerInterface $orm;
    private EntityManagerInterface $autoMapper;
    private string $sql;
    /** @var array<string, string> */
    private array $columns;

    /**
     * @return array<string, array{authors: int}>
     */
    public function provideSizes(): array
    {
        return [
            '3k rows' => ['authors' => 200],
            '15k rows' => ['authors' => 1_000],
        ];
    }

    /**
     * Subjects running a fixed number of queries do not depend on the size of the database.
     *
     * @return array<string, array{authors: int}>
     */
    public function provideSingleSize(): array
    {
        return ['200 queries' => ['authors' => 200]];
    }

    /**
     * @param array{authors: int} $params
     */
    public function setUp(array $params): void
    {
        $database = DoctrineFixture::database($params['authors']);
        $this->orm = DoctrineFixture::entityManager($database);
        $this->autoMapper = DoctrineFixture::entityManager($database, true);
        $this->sql = DoctrineFixture::sql($this->orm);
        $this->columns = DoctrineFixture::columns($this->orm);

        // metadata, DQL parsing and hydrator generation are kept out of the measure
        foreach ([$this->orm, $this->autoMapper] as $em) {
            $em->createQuery(DoctrineFixture::DQL)->setMaxResults(1)->getResult();
            DoctrineFixture::smallQueries($em, 1);
            DoctrineFixture::lazyCollections($em, 1);
            $em->clear();
        }
    }

    #[ParamProviders('provideSizes')]
    public function benchDbalFetch(): void
    {
        $this->orm->getConnection()->executeQuery($this->sql)->fetchAllAssociative();
    }

    #[ParamProviders('provideSizes')]
    public function benchHandwrittenDto(): void
    {
        DoctrineFixture::handwrittenDto($this->orm->getConnection()->executeQuery($this->sql), $this->columns);
    }

    #[ParamProviders('provideSizes')]
    public function benchArrayHydrator(): void
    {
        $this->orm->createQuery(DoctrineFixture::DQL)->getArrayResult();
    }

    #[ParamProviders('provideSizes')]
    public function benchObjectHydrator(): void
    {
        $this->orm->createQuery(DoctrineFixture::DQL)->getResult();
    }

    #[ParamProviders('provideSizes')]
    public function benchAutoMapperHydrator(): void
    {
        $this->autoMapper->createQuery(DoctrineFixture::DQL)->getResult();
    }

    /**
     * 200 queries of 15 rows each.
     */
    #[ParamProviders('provideSingleSize')]
    public function benchObjectHydratorSmallQueries(): void
    {
        DoctrineFixture::smallQueries($this->orm, 200);
    }

    #[ParamProviders('provideSingleSize')]
    public function benchAutoMapperHydratorSmallQueries(): void
    {
        DoctrineFixture::smallQueries($this->autoMapper, 200);
    }

    /**
     * 200 authors, then their books loaded lazily one collection at a time.
     */
    #[ParamProviders('provideSingleSize')]
    public function benchObjectHydratorLazyCollections(): void
    {
        DoctrineFixture::lazyCollections($this->orm, 200);
    }

    #[ParamProviders('provideSingleSize')]
    public function benchAutoMapperHydratorLazyCollections(): void
    {
        DoctrineFixture::lazyCollections($this->autoMapper, 200);
    }
}
